### ISSUE TITLE
Please update the version to 1.20.4.

### ISSUE THREAD

**Issue by excaliburkim** [Valorless/ValorlessUtils#2]
I am using it very well.
Thank you for developing it. :)
Please update the version to 1.20.4.

**Comment by Valorless** [comment]
Once I get home again, I'll build spigot 1.20.4, and begin updating :)

**Comment by Valorless** [comment]
To confirm, as I can't atm myself.
Is it because the plugin doesn't work on 1.20.4, or because it was last updated for 1.20.2?

**Comment by excaliburkim** [comment]
I upgraded from 1.19.2 to 1.20.4.
What worked well in 1.19.2 does not work in 1.20.4. :)

**Comment by Valorless** [comment]
Grettings!
I've had a chance to get Spigot Paper 1.20.4, and had a quick look.
I'm able to start the server and use it with no issues what so ever.

Could you please provide me with your server logs, so I could try and see what is happening?
Another question, which version are you using?
I recently updated the plugin to 1.4.0.132 in Nov.

**Comment by excaliburkim** [comment]
I think I was mistaken. It's working fine now!
thank you! :)
